			<div class="left_container">
				<h1>Bienvenue sur My meetic !</h1>
			<img src="img/home.jpg" alt="photo">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra augue tortor, nec convallis orci luctus et. Suspendisse aliquet ante ut est gravida eleifend. Cras dapibus non sem eget imperdiet. Sed ligula libero, imperdiet at sagittis eget, ultricies non magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc sollicitudin at ipsum eu auctor. Fusce lacus nisl, adipiscing eget pellentesque posuere, mollis a lacus. Praesent et porttitor leo, quis fringilla metus. Ut eu dignissim neque, in rutrum elit.</p>

<p>Nam et nulla at leo egestas varius in eget orci. Proin porta faucibus purus, nec suscipit ipsum aliquet mollis. Nulla pulvinar interdum ligula laoreet fringilla. Etiam tincidunt sagittis tempor. Fusce vel dictum leo. Ut vel elit ac sapien pellentesque interdum nec et risus. In hac habitasse platea dictumst.</p>
<p>Aliquam velit felis, tempus ac fringilla eget, varius non enim. Aliquam vitae felis quis augue condimentum pulvinar nec eget justo. Etiam eget nisi dictum, imperdiet nisi et, congue massa. Aenean congue a ante vel elementum. Curabitur vehicula lectus eu est dictum elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>

<p>Aliquam fermentum consectetur molestie. Phasellus et magna faucibus velit semper semper. Integer nec nulla sed mi sodales scelerisque. Cras quis enim feugiat, dictum neque a, fringilla eros. Aenean faucibus felis in mauris mollis, sit amet tincidunt dolor facilisis. Mauris ut sapien lectus. Nullam id felis nisi. Pellentesque sapien neque, dignissim non tincidunt a, viverra sit amet mi. Mauris mattis ornare accumsan. Ut id posuere enim, non viverra tortor.</p>

<p>Fusce tristique dolor lectus, gravida pellentesque purus dignissim a. Curabitur ut ante rutrum lectus dignissim posuere at et tortor. Aenean elit lectus, tempus eu mauris nec, ullamcorper pellentesque metus. Maecenas varius consectetur eros pretium vestibulum. Integer tempor tempor tincidunt. Mauris placerat ipsum tellus, ac aliquet enim eleifend eget. Etiam et purus laoreet, pellentesque neque eget, accumsan arcu. Vestibulum vitae elit eget erat aliquam mollis ac a lectus. Vestibulum euismod bibendum pellentesque. Nullam ultrices lacus a euismod dictum. Mauris ac turpis vel erat feugiat venenatis quis id diam. Pellentesque egestas eleifend diam. Aliquam urna tortor, elementum at adipiscing id, posuere non sapien. Curabitur congue congue erat nec convallis. Duis nec quam urna.<p>
			</div>
			<div class="right_container">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer viverra augue tortor, nec convallis orci luctus et. Suspendisse aliquet ante ut est gravida eleifend. Cras dapibus non sem eget imperdiet. Sed ligula libero, imperdiet at sagittis eget, ultricies non magna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc sollicitudin at ipsum eu auctor. Fusce lacus nisl, adipiscing eget pellentesque posuere, mollis a lacus. Praesent et porttitor leo, quis fringilla metus. Ut eu dignissim neque, in rutrum elit.</p>

<p>Nam et nulla at leo egestas varius in eget orci. Proin porta faucibus purus, nec suscipit ipsum aliquet mollis. Nulla pulvinar interdum ligula laoreet fringilla. Etiam tincidunt sagittis tempor. Fusce vel dictum leo. Ut vel elit ac sapien pellentesque interdum nec et risus. In hac habitasse platea dictumst.</p>
<p>Aliquam velit felis, tempus ac fringilla eget, varius non enim. Aliquam vitae felis quis augue condimentum pulvinar nec eget justo. Etiam eget nisi dictum, imperdiet nisi et, congue massa. Aenean congue a ante vel elementum. Curabitur vehicula lectus eu est dictum elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>

<p>Aliquam fermentum consectetur molestie. Phasellus et magna faucibus velit semper semper. Integer nec nulla sed mi sodales scelerisque. Cras quis enim feugiat, dictum neque a, fringilla eros. Aenean faucibus felis in mauris mollis, sit amet tincidunt dolor facilisis. Mauris ut sapien lectus. Nullam id felis nisi. Pellentesque sapien neque, dignissim non tincidunt a, viverra sit amet mi. Mauris mattis ornare accumsan. Ut id posuere enim, non viverra tortor.</p>

<p>Fusce tristique dolor lectus, gravida pellentesque purus dignissim a. Curabitur ut ante rutrum lectus dignissim posuere at et tortor. Aenean elit lectus, tempus eu mauris nec, ullamcorper pellentesque metus. Maecenas varius consectetur eros pretium vestibulum. Integer tempor tempor tincidunt. Mauris placerat ipsum tellus, ac aliquet enim eleifend eget. Etiam et purus laoreet, pellentesque neque eget, accumsan arcu. Vestibulum vitae elit eget erat aliquam mollis ac a lectus. Vestibulum euismod bibendum pellentesque. Nullam ultrices lacus a euismod dictum. Mauris ac turpis vel erat feugiat venenatis quis id diam. Pellentesque egestas eleifend diam. Aliquam urna tortor, elementum at adipiscing id, posuere non sapien. Curabitur congue congue erat nec convallis. Duis nec quam urna.<p>
			</div>